### PR TITLE
Fix behavior of wait for week days and day of month

### LINKED ISSUE #16: Weekday and DayOfMonth methods should wait when the day provided is today
### Expected Behavior:
per the discussion with @geomagilles:

if we are on Monday, 11am on the 23rd of the month. Then:

.Monday(1) should wait until next Monday at 11am
.Monday(1).At("9") should wait until next Monday at 9am
.Monday(1).At("13") should wait 2 hours only
.DayOfMonth(23) should wait for one month
.DayOfMonth(23).At("13") should wait for only 2 hours

### Problem:
Currently, if today is a Monday, when calling `(new Wait())->monday()` you don't actually wait until the next Monday, and the wait terminates immediately. 

We have the same issue with the `dayOfMonth` method. If it's the 23rd and you call `(new Wait())->dayOfMonth(23)` you won't wait until the next month, but instead the wait will terminate immediately.

Specifically, I believe the two problematic lines are these: 
https://github.com/zenaton/zenaton-php/blob/a9dfec9462ebeed61bad54031b662d031724b95c/src/Zenaton/v1/Traits/WithTimestamp.php#L165
https://github.com/zenaton/zenaton-php/blob/a9dfec9462ebeed61bad54031b662d031724b95c/src/Zenaton/v1/Traits/WithTimestamp.php#L178

### Fix:
See https://github.com/zenaton/zenaton-go/pull/7 for the fix in the go library.

### PR DESCRIPTION
**Pull request by pylebecq**
When using any of the week day method without specifying any time, it will wait for the next
corresponding week day.

When using any of the week day method and specifying a time, it will wait for the next
corresponding week day except if the week day is the same as today and the specified time is later than the current time.

The behavior for the day of month is similar.

Tests were added to cover all these use cases.

Closes #16

### CODE REVIEW

File: src/Zenaton/v1/Traits/WithTimestamp.php [hunk 1]
```diff
@@ -161,21 +161,28 @@ protected function _dayOfMonth($day, $now, $then)
...
         return $then;
     }
 
-    protected function _weekDay($n, $day, $then)
+    protected function _weekDay($n, $day, $now, $then)
     {
         $this->_setMode(self::$_MODE_WEEK_DAY);
 
+        if ($this->sameWeekDayLater($now, $day)) {
+            --$n;
```
Comment (idabmat) [inline src/Zenaton/v1/Traits/WithTimestamp.php:176]: Does that decrement `$n` by one ?

**Review by idabmat — APPROVED** [review]
:+1: Nice one.

This reminds me I should probably add another test case to the Ruby library.

File: src/Zenaton/v1/Traits/WithTimestamp.php (hunk 1 above)
Comment (pylebecq) [reply src/Zenaton/v1/Traits/WithTimestamp.php:176]: Yes

**Review by Ciboulette — APPROVED** [review]
